version: '3.8'

services:
  app:
    build: .
    container_name: python_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DB=mydatabase
    volumes:
      - ./static:/app/static  # Montar el directorio estático para Swagger

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins  # Usar el Dockerfile personalizado
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  db_data:
  jenkins_home:
